import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { HomeComponent } from './home/home.component.tns';
import { LoginFormComponent } from './account/login-form/login-form.component.tns';
import { NotificationsComponent } from './notifications/notifications/notifications.component.tns';

export const routes: Routes = [
  {
    path: '',
    component: LoginFormComponent

  },
  {
    path: 'land',
    component: HomeComponent,

  },
  {
    path:'notifications',
    component:NotificationsComponent
  }


];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
