import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from './app-routing.module.tns';
import { AppComponent } from './app.component.tns';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ConfigService } from './shared/services/config.service';
import { HttpRequestService } from './shared/services/http-request.service';
import { UserManagerService } from './shared/services/user-manager.service';
import * as mobileStorage from 'nativescript-localstorage';


import { NativeScriptFormsModule } from 'nativescript-angular/forms';

import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { HomeComponent } from './home/home.component.tns';
import { AccountModule } from './account/account.module.tns';
import { NativeScriptUISideDrawerModule } from 'nativescript-ui-sidedrawer/angular';
import { AcademicaffModule } from './academicaff/academicaff.module.tns';
import { GlobalService } from './shared/services/global.service.tns';
import { GlobalBaseService } from './shared/services/global-base.service';
import { AcademicprocsModule } from './academicprocs/academicprocs.module.tns';
import { NativeScriptLocalizeModule } from 'nativescript-localize/angular';
import { AppTransModule } from './app.trans.module.tns';
import { TranslateModule } from '@ngx-translate/core';
import { RegisterCoursesModule } from './register-courses/register-courses.module.tns';
import { FinanceAffairModule } from './finance-affair/finance-affair.module.tns';
import { ExamsAffairModule } from './exams-affair/exams-affair.module.tns';
import { OtherAffairModule } from './other-affair/other-affair.module.tns';
import { MasterAcademicRequestsModule } from './master-academic-requests/master-academic-requests.module.tns';
import { MasterStudentDataModule } from './master-student-data/master-student-data.module.tns';
import { MasterPrintCertificatesModule } from './master-print-certificates/master-print-certificates.module.tns';
import { MasterOtherRequestsModule } from './master-other-requests/master-other-requests.module.tns';
import { NativeScriptUIListViewModule } from 'nativescript-ui-listview/angular';
import { NotificationsComponent } from './notifications/notifications/notifications.component.tns';
import { HeaderModule } from './shared/header.module.tns';
import { PolicyComponent } from './home/policy.component.tns';
import { NewsComponent } from './news/news.component.tns';
import { AdsComponent } from './ads/ads.component.tns';



@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent ,
    HomeComponent,
    NotificationsComponent,
    PolicyComponent,
    NewsComponent,
    AdsComponent
  ],
  imports: [
    AppTransModule,
    NativeScriptModule,
    AppRoutingModule,
    AcademicaffModule,
    NativeScriptHttpClientModule,
    NativeScriptFormsModule,
    AccountModule,
    RegisterCoursesModule,
    AcademicprocsModule,
    NativeScriptUISideDrawerModule,
    AppTransModule,
    FinanceAffairModule,
    ExamsAffairModule,
    OtherAffairModule,
    MasterAcademicRequestsModule,
    MasterStudentDataModule,
    MasterPrintCertificatesModule,
    MasterOtherRequestsModule,
    NativeScriptUIListViewModule,
    HeaderModule
      ],

  providers: [ConfigService, HttpRequestService, UserManagerService,
    {provide: GlobalBaseService, useClass: GlobalService}
  ],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
}


)

/*

Pass your application module to the bootstrapModule function located in main.ts to start your app
*/

export class AppModule { }
