
import { OwlModule } from 'ngx-owl-carousel';
import { AppTransModule } from './app.trans.module';


@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    BlankComponent,
    HeaderComponent,
    AutoGeneratedComponent,
    NameComponentComponent,
    PrintLayoutComponent,
    PrintFileComponent,
    FooterComponent,
    MenuComponent,
    PageHeaderComponent,
    DownloadPrintDirective,
    ExternalLinkDirective
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AngularFontAwesomeModule,
    OwlModule,
    AppTransModule,
    HttpClientModule,
    HttpClientJsonpModule,
    AppRoutingModule,
    AccountModule,
    DashboardModule,
    FormsModule,
    ToastrModule.forRoot(),
    TimerModule,
    MatProgressSpinnerModule
  ],

  providers: [
    ConfigService,
    HttpRequestService,
  ],
  exports: [DownloadPrintDirective, ExternalLinkDirective],
  bootstrap: [AppComponent]
})
export class AppModule {}
