export const environment = {
  production:false,
  cmslink: 'https://seu.edu.sa/umbraco/Surface/',
  //baselink: 'http://eservices.local/', 
  baselink: 'https://seuapps.seu.edu.sa/newservices/', 
  ssolink: 'https://seuapps.seu.edu.sa/newservices/sso', 
  service_json: 'https://seuapps.seu.edu.sa/newservices/api/docs/ServicesInstructions/', //doenlaod and play vedios
  wafi_apilink: 'https://sso.seu.edu.sa/CPTIT_SEU_WS_TEST/jersey/', // wafi
  servie_admission: 'https://apps.seu.edu.sa/newservices/api-test/admission',
  paymentLink: "https://apps.seu.edu.sa/newservices/api-test/fees",
  //common: 'common_api', 
  common: '/rest', 
  ud: 'ud_api', 
  //gr: 'gr_api', 
  gr: '/stdsUnivapi',  
  //servicesprefix: '', 
  servicesprefix: 'api/', 
  appsprefix: 'apps', 
  loginpage: 'login-local.php',
  notesAuth: 'nots:N0t!fic@ti0n$',
  ssoAuth: 'sso:s$0$3u2030',
  allowWafi: true,
  captchaSiteKey: "6LcZJOgUAAAAADeusuP0ndPRe8A5ip1FBypF_WlQ",
  enquery_URL: 'https://intservs.seu.edu.sa/myweb/', // WhatsApp chatbot /
  translation_support_email: '',
  chatbot_mails: [
    'mali@seu.edu.sa', 
    'a.elbery@seu.edu.sa', 
    'm.aldwaesh@seu.edu.sa', 
    'salasmari@seu.edu.sa', 
    'maldwaesh@seu.edu.sa',
    't.alshiban@seu.edu.sa',
    'n.almuhareb@seu.edu.sa',
    'l.alrashed@seu.edu.sa',
    'haltamimy@seu.edu.sa',
    'a.dossari@seu.edu.sa',

    'halhabib@seu.edu.sa',
    'm.albaladi@seu.edu.sa',
    't.aldawish@seu.edu.sa',
    'balsaif@seu.edu.sa',
    'n.almohimid@seu.edu.sa',
    's.abdalwahhb@seu.edu.sa',
    's.abalkhil@seu.edu.sa',
    'f.alswilem@seu.edu.sa',
    'd.alswilem@seu.edu.sa',
    'l.alomari@seu.edu.sa',
    'n.alwahby@seu.edu.sa',
    'halharbi@seu.edu.sa',
    'a.algeffary@seu.edu.sa',
    'a.farouk@seu.edu.sa',
    'o.alturiqi@seu.edu.sa'
  ],
  chatbot_emps_emails: [
    'm.aldwaesh@seu.edu.sa', 
    'salasmari@seu.edu.sa', 
    'maldwaesh@seu.edu.sa',
    't.alshiban@seu.edu.sa',
    'n.almuhareb@seu.edu.sa',
    'l.alrashed@seu.edu.sa',
    'haltamimy@seu.edu.sa',
    'a.dossari@seu.edu.sa',
    
    'halhabib@seu.edu.sa',
    'm.albaladi@seu.edu.sa',
    't.aldawish@seu.edu.sa',
    'balsaif@seu.edu.sa',
    'n.almohimid@seu.edu.sa',
    's.abdalwahhb@seu.edu.sa',
    's.abalkhil@seu.edu.sa',
    'f.alswilem@seu.edu.sa',
    'd.alswilem@seu.edu.sa',
    'l.alomari@seu.edu.sa',
    'n.alwahby@seu.edu.sa',
    'halharbi@seu.edu.sa',
    'a.algeffary@seu.edu.sa',
  ],
  chatbot_emps_names: [
    'موضي مطلق الدويش', 
    'سلمى عبدالله الأسمري', 
    'مضاوي مطلق الدويش',
    'تهاني ناصر الشيبان',
    'نورة فهد المحارب',
    'لما عبداللطيف الراشد',
    'حنان عبدالله التميمي',
    'العنود عبدالله الدوسري',

    'هيلة علي الحبيب',
    'ملاك البلادي',
    'تهاني فلاح الدويش',
    'باسمة صالح السيف',
    'نوف ابراهيم المحيميد',
    'صباح عبدالرحمن عبدالوهاب',
    'سهام سليمان أبالخيل',
    'فاطمة عبدالله سويلم السويلم',
    'دينا عبدالله سويلم السويلم',
    'لولوة ماجد بجاد الحربي',
    'نورة راشد محمد الوهبي',
    'هجوس فهد الحربي ',
    'اميرة سليمان القفاري'
  ],
  chatbot_emps_admins_emails: [
    'a.elbery@seu.edu.sa',
    'haltamimy@seu.edu.sa',
    'a.dossari@seu.edu.sa',
    'a.farouk@seu.edu.sa',
    'o.alturiqi@seu.edu.sa',
    'halhabib@seu.edu.sa',
    't.alshiban@seu.edu.sa',
    'm.albaladi@seu.edu.sa',
  ],
  
};