import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { DashboardModule } from './dashboard/dashboard.module';
import { AccountModule } from './account/account.module';
import { config } from 'rxjs';
import { ConfigService } from './shared/services/config.service';
import {FormsModule} from '@angular/forms';
import { HomeComponent } from './home/home.component';
import { HeaderComponent } from './header/header.component';
import { HttpModule, XHRBackend } from '@angular/http';
import { HttpRequestService } from './shared/services/http-request.service';
import { UserManagerService } from './shared/services/user-manager.service';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { HttpClientModule } from "@angular/common/http";
import { AppStorageService } from './shared/services/app-storage.service';

@NgModule({
  declarations: [
    AppComponent,HomeComponent,HeaderComponent, AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,HttpClientModule,
    AppRoutingModule,AccountModule,DashboardModule,FormsModule
  ],
  providers: [ConfigService,HttpRequestService,UserManagerService,AppStorageService],
  bootstrap: [AppComponent]
})
export class AppModule { }
